<?php

/* ######################################################################
# PP-News v 1.5 Beta                                 15th January 2002  #
# Mailinglist and News for Postnuke                                    #
# PostNuke Conversion by:                                              #
#                          Massimiliano Tiraboschi                     #
#                                                                      #
#           webmaster@postnukeit - www.postnuke.it                     #
#           Italian Support for Postnuke and Open-Source               #
#                                                                      #
 ######################################################################
# Modified version of: 1.5 Beta
 ######################################################################
# PP-News Newsletter                                                   #
# Copyright : (C) 2000, 2001 www.postnuke.it & www.presencenet.net     #
# WWW       : http://www.postnuke.it - http://www.presencenet.net      #
 ######################################################################
#Adaptation to PostNuke Rogue Falco171 || http://www.falco171.net      #
 ######################################################################
# Adaptation to xoops RC2 : Gilles Plume || muple@wanadoo.fr		   #
#######################################################################
# License #
 ######################################################################
# This program is free software; you can redistribute it and/or modify #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation; either version 2 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# This program is distributed in the hope that it will be useful,      #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with this program; if not, write to the Free Software          #
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.            #
# Or just download it http://fsf.org/                                  #
 #####################################################################*/

$modversion['name'] = 'PP-News';
$modversion['version'] = '1.5';
$modversion['description'] = 'Newsletter';
$modversion['credits'] = 'docs/credits.txt';
$modversion['help'] = 'docs/install.txt';
$modversion['changelog'] = 'docs/changelog.txt';
$modversion['license'] = 'docs/license.txt';
$modversion['official'] = 0;
$modversion['author'] = 'Massimiliano Tiraboschi (webmaster@postnuke.it)';
$modversion['contact'] = 'http://www.postnuke.it';
$modversion['image'] = 'PP-News_slogo.jpg';
$modversion['dirname'] = 'PP-News';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;

// Block
$modversion['blocks'][1]['file'] = 'pp-news.php';
$modversion['blocks'][1]['name'] = 'Newsletter';
$modvertion['blocks'][1]['description'] = 'Newsletter';
$modversion['blocks'][1]['show_func'] = 'blocks_ppnews_block';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'pp_newsletter';
